
#ifndef STRUCTURED_AFFIX_H
#define STRUCTURED_AFFIX_H

#define STRUCTURED_POSTFIX2(a, b) a##_##b
#define STRUCTURED_POSTFIX(a, b) STRUCTURED_POSTFIX2(a, b)

#define STRUCTURED_PREFIX(x) STRUCTURED_POSTFIX(structured, x)
#define STRUCTURED_ID(a, b) STRUCTURED_PREFIX(STRUCTURED_POSTFIX(a, b))

#endif